### PR TITLE
Fixes #121 Colorize row with cheaper bin than futbin

### LINKED ISSUE #121: Colorize rows based on different criteria
Hi, are you able to do a similar version of your colorize comparing actual bid price with futbin price?, it will be very good for some of us, thank you for all you've done and fast fifa 19 att =)

### PR DESCRIPTION
**Pull request by Regaddi**
futbin-issue-121-colorize-rows

I'm not 100% sure if I caught every relevant view. Maybe someone can have a double check on these lines https://github.com/Regaddi/futwebapp-tampermonkey/commit/b25c319e6bc1c871046c528f51e32ced2e66f6e7#diff-b4d551ef1f400cbf599b5ae87f5ca2eaR240

### CODE REVIEW

**Comment by Mardaneus86** [comment]
Hmmm, I'd like to get an opinion of someone with color blindness first with this color scheme (red on pink). The selected row should also get a different color when it is cheaper.

**Comment by Regaddi** [comment]
I changed the base branch to `develop` and commit message to `feat: colorize row with cheaper bin than futbin`. I hope that suits better 😄

**Comment by Mardaneus86** [comment]
Hm, I was just looking at this in more detail, but I have already put a commit in de develop branch some days ago that handles a BuyNow vs Futbin check (https://github.com/Mardaneus86/futwebapp-tampermonkey/commit/eaf1ae67ed49943ea89aeaf8fb6189e3f94a49a5). Initially I thought this was marking something else. Can you verify if this is the same?

PS: I've put out a request on the Gitter channel and someone I know that has color blindness to check this. The response from that person was that he had trouble reading the red text.

**Comment by Regaddi** [comment]
Ah ok, I stumbled across the bargain while coding, but didn't know what it was. If this PR gets obsolete, feel free to close it or let's merge both worlds together 😄

**Comment by Mardaneus86** [comment]
I'll do a double check later to if this is exactly the same! Sorry for the confusion.

Thanks again.

**Comment by Mardaneus86** [comment]
Closer investigation showed that this was indeed exactly the same functionality as already implemented in commit https://github.com/Mardaneus86/futwebapp-tampermonkey/commit/eaf1ae67ed49943ea89aeaf8fb6189e3f94a49a5.

Closing because of that reason. Feel free to pick up other open issues in the future!

**Pull request closed without merging**
