### PR TITLE
fix: remove fetch interval on sbc and squad pages

### PR DESCRIPTION
**Pull request by eimarfandino**
fix: https://github.com/Mardaneus86/futwebapp-tampermonkey/issues/199

### CODE REVIEW

**Comment by eimarfandino** [comment]
ok, ready, for SBC and Squad you'll need to do a manual refresh. 
I have also added in this PR pricing for TOTW screen

**Comment by Mardaneus86** [comment]
Please use `develop` as the target branch for PR's. That makes it easier to join several pull requests into a single release.
Also try to keep them targeted on a single change (preferably linked to an issue and no formatting changes), that makes it easier to review them.

Can you change it?

**Comment by eimarfandino** [comment]
@Mardaneus86  sure, not a problem

**Comment by Mardaneus86** [comment]
Sorry for the delay in review. Planned for tomorrow!

**Comment by Mardaneus86** [comment]
Looks good, merging. Thanks!

**Pull request merged**
