### PR TITLE
Update to FUT 20

### PR DESCRIPTION
**Pull request by omursahin**

### CODE REVIEW

**Comment by Mardaneus86** [comment]
Nice work! Only thing that seems to be missing is the settings icon. Could you change the corresponding CSS?

`.futsettings-toggle::before` should become `content: "\E056";` instead of the current `content: "\f139";`

**Comment by omursahin** [comment]
Sure I fixed it.

**Comment by Mardaneus86** [comment]
LGTM

**Comment by gauravbellani** [comment]
hi, im not able to get it to work. can you please guide me on the installation process ? I clicked on that openJS thing and installed it but i dont see the settings icon on the web app

**Pull request merged**
