### PR TITLE
Snipe mode for autobuyer

### PR DESCRIPTION
**Pull request by gianemi2**
Add feature for snipe without select a player name.
This feature is avaiable after click on the new button in autobuyer window named Snipe Mode.

schermata 2017-10-06 alle 10 58 47
schermata 2017-10-06 alle 10 59 00

### CODE REVIEW

**Comment by Mardaneus86** [comment]
I think this will be confusing to users. How will they know that 'Snipe mode' will not check for a specific player name? The auto buyer will still do BIN sniping in any case. If you can figure out a way to make it more obvious in the UI what the option really does, I'm happy to accept the PR.

By the way, you can use jQuery in your solution since the web app already uses that. It will simplify the DOM code.

**Comment by gianemi2** [comment]
All right, I’ll use jQuery! 

I know that “SNIPE MODE” is so unknown. I’m going to think something more obvious. 
The Autobuyer will not BIN sniping in anycase. If you do not insert a name it will return an error.

-- 
Marco Giannini | Web Designer and Developer
Tel: 3299555697 <tel:+393299555697> Email: info@marcogiannini.net <mailto:info@marcogiannini.net>

marcogiannini.net <http://marcogiannini.net/>

**Comment by Mardaneus86** [comment]
Yes I know, what I meant to say was that it only supports BIN sniping and that this would hint to a bidding feature which it does not currently have. If you have questions or want to discuss the feature, you can use the Gitter channel.

**Comment by Mardaneus86** [comment]
#23 replaces this PR

**Pull request closed without merging**
